# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statuses/statuses.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'statuses/statuses.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17statuses/statuses.proto\x12\x10nocloud.statuses\x1a\x1cgoogle/protobuf/struct.proto\"\xe6\x01\n\x06Status\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\x1f.nocloud.statuses.NoCloudStatusR\x06status\x12\x36\n\x04meta\x18\x02 \x03(\x0b\x32\".nocloud.statuses.Status.MetaEntryR\x04meta\x12\x13\n\x02ts\x18\x03 \x01(\x03H\x00R\x02ts\x88\x01\x01\x1aO\n\tMetaEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01\x42\x05\n\x03_ts\"T\n\x0cObjectStatus\x12\x12\n\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x30\n\x06status\x18\x02 \x01(\x0b\x32\x18.nocloud.statuses.StatusR\x06status*t\n\rNoCloudStatus\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04INIT\x10\x01\x12\x0c\n\x08MODIFIED\x10\x02\x12\x06\n\x02UP\x10\x03\x12\x08\n\x04\x44OWN\x10\x04\x12\x07\n\x03\x44\x45L\x10\x05\x12\x08\n\x04PROC\x10\x06\x12\x07\n\x03SUS\x10\x07\x12\x0c\n\x08\x44\x45TACHED\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statuses.statuses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS_METAENTRY']._loaded_options = None
  _globals['_STATUS_METAENTRY']._serialized_options = b'8\001'
  _globals['_NOCLOUDSTATUS']._serialized_start=394
  _globals['_NOCLOUDSTATUS']._serialized_end=510
  _globals['_STATUS']._serialized_start=76
  _globals['_STATUS']._serialized_end=306
  _globals['_STATUS_METAENTRY']._serialized_start=220
  _globals['_STATUS_METAENTRY']._serialized_end=299
  _globals['_OBJECTSTATUS']._serialized_start=308
  _globals['_OBJECTSTATUS']._serialized_end=392
# @@protoc_insertion_point(module_scope)
