//
//Copyright © 2021-2023 Nikita Ivanovski info@slnt-opp.xyz
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: registry/registry.proto

package registry

import (
	context "context"
	notes "github.com/slntopp/nocloud-proto/notes"
	accounts "github.com/slntopp/nocloud-proto/registry/accounts"
	namespaces "github.com/slntopp/nocloud-proto/registry/namespaces"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountsService_Token_FullMethodName          = "/nocloud.registry.AccountsService/Token"
	AccountsService_SetCredentials_FullMethodName = "/nocloud.registry.AccountsService/SetCredentials"
	AccountsService_AddNote_FullMethodName        = "/nocloud.registry.AccountsService/AddNote"
	AccountsService_PatchNote_FullMethodName      = "/nocloud.registry.AccountsService/PatchNote"
	AccountsService_RemoveNote_FullMethodName     = "/nocloud.registry.AccountsService/RemoveNote"
	AccountsService_Create_FullMethodName         = "/nocloud.registry.AccountsService/Create"
	AccountsService_StandartCreate_FullMethodName = "/nocloud.registry.AccountsService/StandartCreate"
	AccountsService_Update_FullMethodName         = "/nocloud.registry.AccountsService/Update"
	AccountsService_Get_FullMethodName            = "/nocloud.registry.AccountsService/Get"
	AccountsService_List_FullMethodName           = "/nocloud.registry.AccountsService/List"
	AccountsService_Delete_FullMethodName         = "/nocloud.registry.AccountsService/Delete"
	AccountsService_Suspend_FullMethodName        = "/nocloud.registry.AccountsService/Suspend"
	AccountsService_Unsuspend_FullMethodName      = "/nocloud.registry.AccountsService/Unsuspend"
)

// AccountsServiceClient is the client API for AccountsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountsServiceClient interface {
	Token(ctx context.Context, in *accounts.TokenRequest, opts ...grpc.CallOption) (*accounts.TokenResponse, error)
	SetCredentials(ctx context.Context, in *accounts.SetCredentialsRequest, opts ...grpc.CallOption) (*accounts.SetCredentialsResponse, error)
	AddNote(ctx context.Context, in *notes.AddNoteRequest, opts ...grpc.CallOption) (*notes.NoteResponse, error)
	PatchNote(ctx context.Context, in *notes.PatchNoteRequest, opts ...grpc.CallOption) (*notes.NoteResponse, error)
	RemoveNote(ctx context.Context, in *notes.RemoveNoteRequest, opts ...grpc.CallOption) (*notes.NoteResponse, error)
	Create(ctx context.Context, in *accounts.CreateRequest, opts ...grpc.CallOption) (*accounts.CreateResponse, error)
	StandartCreate(ctx context.Context, in *accounts.CreateRequest, opts ...grpc.CallOption) (*accounts.CreateResponse, error)
	Update(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.UpdateResponse, error)
	Get(ctx context.Context, in *accounts.GetRequest, opts ...grpc.CallOption) (*accounts.Account, error)
	List(ctx context.Context, in *accounts.ListRequest, opts ...grpc.CallOption) (*accounts.ListResponse, error)
	Delete(ctx context.Context, in *accounts.DeleteRequest, opts ...grpc.CallOption) (*accounts.DeleteResponse, error)
	Suspend(ctx context.Context, in *accounts.SuspendRequest, opts ...grpc.CallOption) (*accounts.SuspendResponse, error)
	Unsuspend(ctx context.Context, in *accounts.UnsuspendRequest, opts ...grpc.CallOption) (*accounts.UnsuspendResponse, error)
}

type accountsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsServiceClient(cc grpc.ClientConnInterface) AccountsServiceClient {
	return &accountsServiceClient{cc}
}

func (c *accountsServiceClient) Token(ctx context.Context, in *accounts.TokenRequest, opts ...grpc.CallOption) (*accounts.TokenResponse, error) {
	out := new(accounts.TokenResponse)
	err := c.cc.Invoke(ctx, AccountsService_Token_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) SetCredentials(ctx context.Context, in *accounts.SetCredentialsRequest, opts ...grpc.CallOption) (*accounts.SetCredentialsResponse, error) {
	out := new(accounts.SetCredentialsResponse)
	err := c.cc.Invoke(ctx, AccountsService_SetCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) AddNote(ctx context.Context, in *notes.AddNoteRequest, opts ...grpc.CallOption) (*notes.NoteResponse, error) {
	out := new(notes.NoteResponse)
	err := c.cc.Invoke(ctx, AccountsService_AddNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) PatchNote(ctx context.Context, in *notes.PatchNoteRequest, opts ...grpc.CallOption) (*notes.NoteResponse, error) {
	out := new(notes.NoteResponse)
	err := c.cc.Invoke(ctx, AccountsService_PatchNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) RemoveNote(ctx context.Context, in *notes.RemoveNoteRequest, opts ...grpc.CallOption) (*notes.NoteResponse, error) {
	out := new(notes.NoteResponse)
	err := c.cc.Invoke(ctx, AccountsService_RemoveNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Create(ctx context.Context, in *accounts.CreateRequest, opts ...grpc.CallOption) (*accounts.CreateResponse, error) {
	out := new(accounts.CreateResponse)
	err := c.cc.Invoke(ctx, AccountsService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) StandartCreate(ctx context.Context, in *accounts.CreateRequest, opts ...grpc.CallOption) (*accounts.CreateResponse, error) {
	out := new(accounts.CreateResponse)
	err := c.cc.Invoke(ctx, AccountsService_StandartCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Update(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.UpdateResponse, error) {
	out := new(accounts.UpdateResponse)
	err := c.cc.Invoke(ctx, AccountsService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Get(ctx context.Context, in *accounts.GetRequest, opts ...grpc.CallOption) (*accounts.Account, error) {
	out := new(accounts.Account)
	err := c.cc.Invoke(ctx, AccountsService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) List(ctx context.Context, in *accounts.ListRequest, opts ...grpc.CallOption) (*accounts.ListResponse, error) {
	out := new(accounts.ListResponse)
	err := c.cc.Invoke(ctx, AccountsService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Delete(ctx context.Context, in *accounts.DeleteRequest, opts ...grpc.CallOption) (*accounts.DeleteResponse, error) {
	out := new(accounts.DeleteResponse)
	err := c.cc.Invoke(ctx, AccountsService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Suspend(ctx context.Context, in *accounts.SuspendRequest, opts ...grpc.CallOption) (*accounts.SuspendResponse, error) {
	out := new(accounts.SuspendResponse)
	err := c.cc.Invoke(ctx, AccountsService_Suspend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Unsuspend(ctx context.Context, in *accounts.UnsuspendRequest, opts ...grpc.CallOption) (*accounts.UnsuspendResponse, error) {
	out := new(accounts.UnsuspendResponse)
	err := c.cc.Invoke(ctx, AccountsService_Unsuspend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServiceServer is the server API for AccountsService service.
// All implementations must embed UnimplementedAccountsServiceServer
// for forward compatibility
type AccountsServiceServer interface {
	Token(context.Context, *accounts.TokenRequest) (*accounts.TokenResponse, error)
	SetCredentials(context.Context, *accounts.SetCredentialsRequest) (*accounts.SetCredentialsResponse, error)
	AddNote(context.Context, *notes.AddNoteRequest) (*notes.NoteResponse, error)
	PatchNote(context.Context, *notes.PatchNoteRequest) (*notes.NoteResponse, error)
	RemoveNote(context.Context, *notes.RemoveNoteRequest) (*notes.NoteResponse, error)
	Create(context.Context, *accounts.CreateRequest) (*accounts.CreateResponse, error)
	StandartCreate(context.Context, *accounts.CreateRequest) (*accounts.CreateResponse, error)
	Update(context.Context, *accounts.Account) (*accounts.UpdateResponse, error)
	Get(context.Context, *accounts.GetRequest) (*accounts.Account, error)
	List(context.Context, *accounts.ListRequest) (*accounts.ListResponse, error)
	Delete(context.Context, *accounts.DeleteRequest) (*accounts.DeleteResponse, error)
	Suspend(context.Context, *accounts.SuspendRequest) (*accounts.SuspendResponse, error)
	Unsuspend(context.Context, *accounts.UnsuspendRequest) (*accounts.UnsuspendResponse, error)
	mustEmbedUnimplementedAccountsServiceServer()
}

// UnimplementedAccountsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountsServiceServer struct {
}

func (UnimplementedAccountsServiceServer) Token(context.Context, *accounts.TokenRequest) (*accounts.TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (UnimplementedAccountsServiceServer) SetCredentials(context.Context, *accounts.SetCredentialsRequest) (*accounts.SetCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCredentials not implemented")
}
func (UnimplementedAccountsServiceServer) AddNote(context.Context, *notes.AddNoteRequest) (*notes.NoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNote not implemented")
}
func (UnimplementedAccountsServiceServer) PatchNote(context.Context, *notes.PatchNoteRequest) (*notes.NoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchNote not implemented")
}
func (UnimplementedAccountsServiceServer) RemoveNote(context.Context, *notes.RemoveNoteRequest) (*notes.NoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNote not implemented")
}
func (UnimplementedAccountsServiceServer) Create(context.Context, *accounts.CreateRequest) (*accounts.CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAccountsServiceServer) StandartCreate(context.Context, *accounts.CreateRequest) (*accounts.CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StandartCreate not implemented")
}
func (UnimplementedAccountsServiceServer) Update(context.Context, *accounts.Account) (*accounts.UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAccountsServiceServer) Get(context.Context, *accounts.GetRequest) (*accounts.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccountsServiceServer) List(context.Context, *accounts.ListRequest) (*accounts.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccountsServiceServer) Delete(context.Context, *accounts.DeleteRequest) (*accounts.DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAccountsServiceServer) Suspend(context.Context, *accounts.SuspendRequest) (*accounts.SuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suspend not implemented")
}
func (UnimplementedAccountsServiceServer) Unsuspend(context.Context, *accounts.UnsuspendRequest) (*accounts.UnsuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsuspend not implemented")
}
func (UnimplementedAccountsServiceServer) mustEmbedUnimplementedAccountsServiceServer() {}

// UnsafeAccountsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountsServiceServer will
// result in compilation errors.
type UnsafeAccountsServiceServer interface {
	mustEmbedUnimplementedAccountsServiceServer()
}

func RegisterAccountsServiceServer(s grpc.ServiceRegistrar, srv AccountsServiceServer) {
	s.RegisterService(&AccountsService_ServiceDesc, srv)
}

func _AccountsService_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Token(ctx, req.(*accounts.TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_SetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.SetCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).SetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_SetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).SetCredentials(ctx, req.(*accounts.SetCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_AddNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(notes.AddNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).AddNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_AddNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).AddNote(ctx, req.(*notes.AddNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_PatchNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(notes.PatchNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).PatchNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_PatchNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).PatchNote(ctx, req.(*notes.PatchNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_RemoveNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(notes.RemoveNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).RemoveNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_RemoveNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).RemoveNote(ctx, req.(*notes.RemoveNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Create(ctx, req.(*accounts.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_StandartCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).StandartCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_StandartCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).StandartCreate(ctx, req.(*accounts.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Update(ctx, req.(*accounts.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Get(ctx, req.(*accounts.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).List(ctx, req.(*accounts.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Delete(ctx, req.(*accounts.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Suspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Suspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Suspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Suspend(ctx, req.(*accounts.SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Unsuspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.UnsuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Unsuspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Unsuspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Unsuspend(ctx, req.(*accounts.UnsuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountsService_ServiceDesc is the grpc.ServiceDesc for AccountsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nocloud.registry.AccountsService",
	HandlerType: (*AccountsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Token",
			Handler:    _AccountsService_Token_Handler,
		},
		{
			MethodName: "SetCredentials",
			Handler:    _AccountsService_SetCredentials_Handler,
		},
		{
			MethodName: "AddNote",
			Handler:    _AccountsService_AddNote_Handler,
		},
		{
			MethodName: "PatchNote",
			Handler:    _AccountsService_PatchNote_Handler,
		},
		{
			MethodName: "RemoveNote",
			Handler:    _AccountsService_RemoveNote_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountsService_Create_Handler,
		},
		{
			MethodName: "StandartCreate",
			Handler:    _AccountsService_StandartCreate_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountsService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountsService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AccountsService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountsService_Delete_Handler,
		},
		{
			MethodName: "Suspend",
			Handler:    _AccountsService_Suspend_Handler,
		},
		{
			MethodName: "Unsuspend",
			Handler:    _AccountsService_Unsuspend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry/registry.proto",
}

const (
	NamespacesService_Create_FullMethodName = "/nocloud.registry.NamespacesService/Create"
	NamespacesService_List_FullMethodName   = "/nocloud.registry.NamespacesService/List"
	NamespacesService_Join_FullMethodName   = "/nocloud.registry.NamespacesService/Join"
	NamespacesService_Link_FullMethodName   = "/nocloud.registry.NamespacesService/Link"
	NamespacesService_Delete_FullMethodName = "/nocloud.registry.NamespacesService/Delete"
	NamespacesService_Patch_FullMethodName  = "/nocloud.registry.NamespacesService/Patch"
)

// NamespacesServiceClient is the client API for NamespacesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamespacesServiceClient interface {
	Create(ctx context.Context, in *namespaces.CreateRequest, opts ...grpc.CallOption) (*namespaces.CreateResponse, error)
	List(ctx context.Context, in *namespaces.ListRequest, opts ...grpc.CallOption) (*namespaces.ListResponse, error)
	Join(ctx context.Context, in *namespaces.JoinRequest, opts ...grpc.CallOption) (*namespaces.JoinResponse, error)
	Link(ctx context.Context, in *namespaces.LinkRequest, opts ...grpc.CallOption) (*namespaces.LinkResponse, error)
	Delete(ctx context.Context, in *namespaces.DeleteRequest, opts ...grpc.CallOption) (*namespaces.DeleteResponse, error)
	Patch(ctx context.Context, in *namespaces.PatchRequest, opts ...grpc.CallOption) (*namespaces.PatchResponse, error)
}

type namespacesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamespacesServiceClient(cc grpc.ClientConnInterface) NamespacesServiceClient {
	return &namespacesServiceClient{cc}
}

func (c *namespacesServiceClient) Create(ctx context.Context, in *namespaces.CreateRequest, opts ...grpc.CallOption) (*namespaces.CreateResponse, error) {
	out := new(namespaces.CreateResponse)
	err := c.cc.Invoke(ctx, NamespacesService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) List(ctx context.Context, in *namespaces.ListRequest, opts ...grpc.CallOption) (*namespaces.ListResponse, error) {
	out := new(namespaces.ListResponse)
	err := c.cc.Invoke(ctx, NamespacesService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Join(ctx context.Context, in *namespaces.JoinRequest, opts ...grpc.CallOption) (*namespaces.JoinResponse, error) {
	out := new(namespaces.JoinResponse)
	err := c.cc.Invoke(ctx, NamespacesService_Join_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Link(ctx context.Context, in *namespaces.LinkRequest, opts ...grpc.CallOption) (*namespaces.LinkResponse, error) {
	out := new(namespaces.LinkResponse)
	err := c.cc.Invoke(ctx, NamespacesService_Link_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Delete(ctx context.Context, in *namespaces.DeleteRequest, opts ...grpc.CallOption) (*namespaces.DeleteResponse, error) {
	out := new(namespaces.DeleteResponse)
	err := c.cc.Invoke(ctx, NamespacesService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Patch(ctx context.Context, in *namespaces.PatchRequest, opts ...grpc.CallOption) (*namespaces.PatchResponse, error) {
	out := new(namespaces.PatchResponse)
	err := c.cc.Invoke(ctx, NamespacesService_Patch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespacesServiceServer is the server API for NamespacesService service.
// All implementations must embed UnimplementedNamespacesServiceServer
// for forward compatibility
type NamespacesServiceServer interface {
	Create(context.Context, *namespaces.CreateRequest) (*namespaces.CreateResponse, error)
	List(context.Context, *namespaces.ListRequest) (*namespaces.ListResponse, error)
	Join(context.Context, *namespaces.JoinRequest) (*namespaces.JoinResponse, error)
	Link(context.Context, *namespaces.LinkRequest) (*namespaces.LinkResponse, error)
	Delete(context.Context, *namespaces.DeleteRequest) (*namespaces.DeleteResponse, error)
	Patch(context.Context, *namespaces.PatchRequest) (*namespaces.PatchResponse, error)
	mustEmbedUnimplementedNamespacesServiceServer()
}

// UnimplementedNamespacesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNamespacesServiceServer struct {
}

func (UnimplementedNamespacesServiceServer) Create(context.Context, *namespaces.CreateRequest) (*namespaces.CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNamespacesServiceServer) List(context.Context, *namespaces.ListRequest) (*namespaces.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNamespacesServiceServer) Join(context.Context, *namespaces.JoinRequest) (*namespaces.JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedNamespacesServiceServer) Link(context.Context, *namespaces.LinkRequest) (*namespaces.LinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Link not implemented")
}
func (UnimplementedNamespacesServiceServer) Delete(context.Context, *namespaces.DeleteRequest) (*namespaces.DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNamespacesServiceServer) Patch(context.Context, *namespaces.PatchRequest) (*namespaces.PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedNamespacesServiceServer) mustEmbedUnimplementedNamespacesServiceServer() {}

// UnsafeNamespacesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamespacesServiceServer will
// result in compilation errors.
type UnsafeNamespacesServiceServer interface {
	mustEmbedUnimplementedNamespacesServiceServer()
}

func RegisterNamespacesServiceServer(s grpc.ServiceRegistrar, srv NamespacesServiceServer) {
	s.RegisterService(&NamespacesService_ServiceDesc, srv)
}

func _NamespacesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Create(ctx, req.(*namespaces.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).List(ctx, req.(*namespaces.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Join(ctx, req.(*namespaces.JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Link_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Link(ctx, req.(*namespaces.LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Delete(ctx, req.(*namespaces.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.PatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Patch(ctx, req.(*namespaces.PatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NamespacesService_ServiceDesc is the grpc.ServiceDesc for NamespacesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamespacesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nocloud.registry.NamespacesService",
	HandlerType: (*NamespacesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NamespacesService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NamespacesService_List_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _NamespacesService_Join_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _NamespacesService_Link_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NamespacesService_Delete_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _NamespacesService_Patch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry/registry.proto",
}
