// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: billing/descriptions/descriptions.proto

package descriptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Description struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Description) Reset() {
	*x = Description{}
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Description) ProtoMessage() {}

func (x *Description) ProtoReflect() protoreflect.Message {
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Description.ProtoReflect.Descriptor instead.
func (*Description) Descriptor() ([]byte, []int) {
	return file_billing_descriptions_descriptions_proto_rawDescGZIP(), []int{0}
}

func (x *Description) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Description) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListDescriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *uint64                `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *uint64                `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Field         *string                `protobuf:"bytes,3,opt,name=field,proto3,oneof" json:"field,omitempty"`
	Sort          *string                `protobuf:"bytes,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDescriptionsRequest) Reset() {
	*x = ListDescriptionsRequest{}
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDescriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDescriptionsRequest) ProtoMessage() {}

func (x *ListDescriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDescriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListDescriptionsRequest) Descriptor() ([]byte, []int) {
	return file_billing_descriptions_descriptions_proto_rawDescGZIP(), []int{1}
}

func (x *ListDescriptionsRequest) GetPage() uint64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListDescriptionsRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListDescriptionsRequest) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *ListDescriptionsRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

type CountDescriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountDescriptionsRequest) Reset() {
	*x = CountDescriptionsRequest{}
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountDescriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountDescriptionsRequest) ProtoMessage() {}

func (x *CountDescriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountDescriptionsRequest.ProtoReflect.Descriptor instead.
func (*CountDescriptionsRequest) Descriptor() ([]byte, []int) {
	return file_billing_descriptions_descriptions_proto_rawDescGZIP(), []int{2}
}

type CountDescriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountDescriptionsResponse) Reset() {
	*x = CountDescriptionsResponse{}
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountDescriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountDescriptionsResponse) ProtoMessage() {}

func (x *CountDescriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountDescriptionsResponse.ProtoReflect.Descriptor instead.
func (*CountDescriptionsResponse) Descriptor() ([]byte, []int) {
	return file_billing_descriptions_descriptions_proto_rawDescGZIP(), []int{3}
}

func (x *CountDescriptionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListDescriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptions  []*Description         `protobuf:"bytes,1,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDescriptionsResponse) Reset() {
	*x = ListDescriptionsResponse{}
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDescriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDescriptionsResponse) ProtoMessage() {}

func (x *ListDescriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_descriptions_descriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDescriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListDescriptionsResponse) Descriptor() ([]byte, []int) {
	return file_billing_descriptions_descriptions_proto_rawDescGZIP(), []int{4}
}

func (x *ListDescriptionsResponse) GetDescriptions() []*Description {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

var File_billing_descriptions_descriptions_proto protoreflect.FileDescriptor

const file_billing_descriptions_descriptions_proto_rawDesc = "" +
	"\n" +
	"'billing/descriptions/descriptions.proto\x12\x1cnocloud.billing.descriptions\x1a\x1cgoogle/protobuf/struct.proto\"5\n" +
	"\vDescription\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xa7\x01\n" +
	"\x17ListDescriptionsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x04H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x04H\x01R\x05limit\x88\x01\x01\x12\x19\n" +
	"\x05field\x18\x03 \x01(\tH\x02R\x05field\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\tH\x03R\x04sort\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\b\n" +
	"\x06_fieldB\a\n" +
	"\x05_sort\"\x1a\n" +
	"\x18CountDescriptionsRequest\"1\n" +
	"\x19CountDescriptionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"i\n" +
	"\x18ListDescriptionsResponse\x12M\n" +
	"\fdescriptions\x18\x01 \x03(\v2).nocloud.billing.descriptions.DescriptionR\fdescriptionsB\xfe\x01\n" +
	" com.nocloud.billing.descriptionsB\x11DescriptionsProtoP\x01Z5github.com/slntopp/nocloud-proto/billing/descriptions\xa2\x02\x03NBD\xaa\x02\x1cNocloud.Billing.Descriptions\xca\x02\x1cNocloud\\Billing\\Descriptions\xe2\x02(Nocloud\\Billing\\Descriptions\\GPBMetadata\xea\x02\x1eNocloud::Billing::Descriptionsb\x06proto3"

var (
	file_billing_descriptions_descriptions_proto_rawDescOnce sync.Once
	file_billing_descriptions_descriptions_proto_rawDescData []byte
)

func file_billing_descriptions_descriptions_proto_rawDescGZIP() []byte {
	file_billing_descriptions_descriptions_proto_rawDescOnce.Do(func() {
		file_billing_descriptions_descriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_descriptions_descriptions_proto_rawDesc), len(file_billing_descriptions_descriptions_proto_rawDesc)))
	})
	return file_billing_descriptions_descriptions_proto_rawDescData
}

var file_billing_descriptions_descriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_descriptions_descriptions_proto_goTypes = []any{
	(*Description)(nil),               // 0: nocloud.billing.descriptions.Description
	(*ListDescriptionsRequest)(nil),   // 1: nocloud.billing.descriptions.ListDescriptionsRequest
	(*CountDescriptionsRequest)(nil),  // 2: nocloud.billing.descriptions.CountDescriptionsRequest
	(*CountDescriptionsResponse)(nil), // 3: nocloud.billing.descriptions.CountDescriptionsResponse
	(*ListDescriptionsResponse)(nil),  // 4: nocloud.billing.descriptions.ListDescriptionsResponse
}
var file_billing_descriptions_descriptions_proto_depIdxs = []int32{
	0, // 0: nocloud.billing.descriptions.ListDescriptionsResponse.descriptions:type_name -> nocloud.billing.descriptions.Description
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_billing_descriptions_descriptions_proto_init() }
func file_billing_descriptions_descriptions_proto_init() {
	if File_billing_descriptions_descriptions_proto != nil {
		return
	}
	file_billing_descriptions_descriptions_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_descriptions_descriptions_proto_rawDesc), len(file_billing_descriptions_descriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_billing_descriptions_descriptions_proto_goTypes,
		DependencyIndexes: file_billing_descriptions_descriptions_proto_depIdxs,
		MessageInfos:      file_billing_descriptions_descriptions_proto_msgTypes,
	}.Build()
	File_billing_descriptions_descriptions_proto = out.File
	file_billing_descriptions_descriptions_proto_goTypes = nil
	file_billing_descriptions_descriptions_proto_depIdxs = nil
}
