<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notes/notes.proto

namespace Nocloud\Notes\GPBMetadata;

class Notes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
³
notes/notes.protonocloud.notes"g
	AdminNote
admin (	Radmin
msg (	Rmsg
created (Rcreated
updated (Rupdated"6
AddNoteRequest
uuid (	Ruuid
msg (	Rmsg"N
PatchNoteRequest
uuid (	Ruuid
index (Rindex
msg (	Rmsg"=
RemoveNoteRequest
uuid (	Ruuid
index (Rindex"a
NoteResponse
result (Rresult9
admin_notes (2.nocloud.notes.AdminNoteR
adminNotesBt
com.nocloud.notesB
NotesProtoP¢NNXªNocloud.NotesÊNocloud\\NotesâNocloud\\Notes\\GPBMetadataêNocloud::Notesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

