<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing/descriptions/descriptions.proto

namespace Nocloud\Billing\Descriptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.billing.descriptions.ListDescriptionsRequest</code>
 */
class ListDescriptionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint64 page = 1 [json_name = "page"];</code>
     */
    protected $page = null;
    /**
     * Generated from protobuf field <code>optional uint64 limit = 2 [json_name = "limit"];</code>
     */
    protected $limit = null;
    /**
     * Generated from protobuf field <code>optional string field = 3 [json_name = "field"];</code>
     */
    protected $field = null;
    /**
     * Generated from protobuf field <code>optional string sort = 4 [json_name = "sort"];</code>
     */
    protected $sort = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $page
     *     @type int|string $limit
     *     @type string $field
     *     @type string $sort
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Billing\Descriptions\GPBMetadata\Descriptions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint64 page = 1 [json_name = "page"];</code>
     * @return int|string
     */
    public function getPage()
    {
        return isset($this->page) ? $this->page : 0;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>optional uint64 page = 1 [json_name = "page"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkUint64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 limit = 2 [json_name = "limit"];</code>
     * @return int|string
     */
    public function getLimit()
    {
        return isset($this->limit) ? $this->limit : 0;
    }

    public function hasLimit()
    {
        return isset($this->limit);
    }

    public function clearLimit()
    {
        unset($this->limit);
    }

    /**
     * Generated from protobuf field <code>optional uint64 limit = 2 [json_name = "limit"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string field = 3 [json_name = "field"];</code>
     * @return string
     */
    public function getField()
    {
        return isset($this->field) ? $this->field : '';
    }

    public function hasField()
    {
        return isset($this->field);
    }

    public function clearField()
    {
        unset($this->field);
    }

    /**
     * Generated from protobuf field <code>optional string field = 3 [json_name = "field"];</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string sort = 4 [json_name = "sort"];</code>
     * @return string
     */
    public function getSort()
    {
        return isset($this->sort) ? $this->sort : '';
    }

    public function hasSort()
    {
        return isset($this->sort);
    }

    public function clearSort()
    {
        unset($this->sort);
    }

    /**
     * Generated from protobuf field <code>optional string sort = 4 [json_name = "sort"];</code>
     * @param string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort = $var;

        return $this;
    }

}

