<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sessions/sessions.proto

namespace Nocloud\Sessions\GPBMetadata;

class Sessions
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x81\x08\x0A\x17sessions/sessions.proto\x12\x10nocloud.sessions\"\x0E\x0A\x0CEmptyMessage\"\x10\x0A\x0EDeleteResponse\"\xD9\x01\x0A\x07Session\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02id\x12\x16\x0A\x06client\x18\x02 \x01(\x09R\x06client\x129\x0A\x07expires\x18\x03 \x01(\x0B2\x1A.google.protobuf.TimestampH\x00R\x07expires\x88\x01\x01\x124\x0A\x07created\x18\x04 \x01(\x0B2\x1A.google.protobuf.TimestampR\x07created\x12\x1D\x0A\x07current\x18\x05 \x01(\x08H\x01R\x07current\x88\x01\x01B\x0A\x0A\x08_expiresB\x0A\x0A\x08_current\"\xAA\x01\x0A\x08Activity\x12E\x0A\x09last_seen\x18\x01 \x03(\x0B2(.nocloud.sessions.Activity.LastSeenEntryR\x08lastSeen\x1AW\x0A\x0DLastSeenEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x120\x0A\x05value\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x05value:\x028\x01\"A\x0A\x08Sessions\x125\x0A\x08sessions\x18\x01 \x03(\x0B2\x19.nocloud.sessions.SessionR\x08sessions\"7\x0A\x0BGetSessions\x12\x1C\x0A\x07user_id\x18\x01 \x01(\x09H\x00R\x06userId\x88\x01\x01B\x0A\x0A\x08_user_id\"(\x0A\x12GetActivityRequest\x12\x12\x0A\x04uuid\x18\x01 \x01(\x09R\x04uuid2\xF1\x01\x0A\x0FSessionsService\x12B\x0A\x03Get\x12\x1D.nocloud.sessions.GetSessions\x1A\x1A.nocloud.sessions.Sessions\"\x00\x12G\x0A\x06Revoke\x12\x19.nocloud.sessions.Session\x1A .nocloud.sessions.DeleteResponse\"\x00\x12Q\x0A\x0BGetActivity\x12\$.nocloud.sessions.GetActivityRequest\x1A\x1A.nocloud.sessions.Activity\"\x00B\x86\x01\x0A\x14com.nocloud.sessionsB\x0DSessionsProtoP\x01\xA2\x02\x03NSX\xAA\x02\x10Nocloud.Sessions\xCA\x02\x10Nocloud\\Sessions\xE2\x02\x1CNocloud\\Sessions\\GPBMetadata\xEA\x02\x11Nocloud::Sessionsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

