<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry/accounts/accounts.proto

namespace Nocloud\Registry\Accounts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.registry.accounts.AccountNotification</code>
 */
class AccountNotification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     */
    protected $disabled = null;
    /**
     * Generated from protobuf field <code>int64 last_notification = 2 [json_name = "lastNotification"];</code>
     */
    protected $last_notification = 0;
    /**
     * Generated from protobuf field <code>int64 sent_notifications = 3 [json_name = "sentNotifications"];</code>
     */
    protected $sent_notifications = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $disabled
     *     @type int|string $last_notification
     *     @type int|string $sent_notifications
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Registry\Accounts\GPBMetadata\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     * @return bool
     */
    public function getDisabled()
    {
        return isset($this->disabled) ? $this->disabled : false;
    }

    public function hasDisabled()
    {
        return isset($this->disabled);
    }

    public function clearDisabled()
    {
        unset($this->disabled);
    }

    /**
     * Generated from protobuf field <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     * @param bool $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_notification = 2 [json_name = "lastNotification"];</code>
     * @return int|string
     */
    public function getLastNotification()
    {
        return $this->last_notification;
    }

    /**
     * Generated from protobuf field <code>int64 last_notification = 2 [json_name = "lastNotification"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastNotification($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_notification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sent_notifications = 3 [json_name = "sentNotifications"];</code>
     * @return int|string
     */
    public function getSentNotifications()
    {
        return $this->sent_notifications;
    }

    /**
     * Generated from protobuf field <code>int64 sent_notifications = 3 [json_name = "sentNotifications"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSentNotifications($var)
    {
        GPBUtil::checkInt64($var);
        $this->sent_notifications = $var;

        return $this;
    }

}

