<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry/accounts/accounts.proto

namespace Nocloud\Registry\Accounts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.registry.accounts.BalanceNotification</code>
 */
class BalanceNotification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nocloud.registry.accounts.AccountNotification base = 1 [json_name = "base"];</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>optional bool invalidated = 2 [json_name = "invalidated"];</code>
     */
    protected $invalidated = null;
    /**
     * Generated from protobuf field <code>optional double threshold = 3 [json_name = "threshold"];</code>
     */
    protected $threshold = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nocloud\Registry\Accounts\AccountNotification $base
     *     @type bool $invalidated
     *     @type float $threshold
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Registry\Accounts\GPBMetadata\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nocloud.registry.accounts.AccountNotification base = 1 [json_name = "base"];</code>
     * @return \Nocloud\Registry\Accounts\AccountNotification|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.nocloud.registry.accounts.AccountNotification base = 1 [json_name = "base"];</code>
     * @param \Nocloud\Registry\Accounts\AccountNotification $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Nocloud\Registry\Accounts\AccountNotification::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool invalidated = 2 [json_name = "invalidated"];</code>
     * @return bool
     */
    public function getInvalidated()
    {
        return isset($this->invalidated) ? $this->invalidated : false;
    }

    public function hasInvalidated()
    {
        return isset($this->invalidated);
    }

    public function clearInvalidated()
    {
        unset($this->invalidated);
    }

    /**
     * Generated from protobuf field <code>optional bool invalidated = 2 [json_name = "invalidated"];</code>
     * @param bool $var
     * @return $this
     */
    public function setInvalidated($var)
    {
        GPBUtil::checkBool($var);
        $this->invalidated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double threshold = 3 [json_name = "threshold"];</code>
     * @return float
     */
    public function getThreshold()
    {
        return isset($this->threshold) ? $this->threshold : 0.0;
    }

    public function hasThreshold()
    {
        return isset($this->threshold);
    }

    public function clearThreshold()
    {
        unset($this->threshold);
    }

    /**
     * Generated from protobuf field <code>optional double threshold = 3 [json_name = "threshold"];</code>
     * @param float $var
     * @return $this
     */
    public function setThreshold($var)
    {
        GPBUtil::checkDouble($var);
        $this->threshold = $var;

        return $this;
    }

}

