# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sessions import sessions_pb2 as sessions_dot_sessions__pb2


class SessionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/nocloud.sessions.SessionsService/Get',
                request_serializer=sessions_dot_sessions__pb2.GetSessions.SerializeToString,
                response_deserializer=sessions_dot_sessions__pb2.Sessions.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/nocloud.sessions.SessionsService/Revoke',
                request_serializer=sessions_dot_sessions__pb2.Session.SerializeToString,
                response_deserializer=sessions_dot_sessions__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetActivity = channel.unary_unary(
                '/nocloud.sessions.SessionsService/GetActivity',
                request_serializer=sessions_dot_sessions__pb2.GetActivityRequest.SerializeToString,
                response_deserializer=sessions_dot_sessions__pb2.Activity.FromString,
                _registered_method=True)


class SessionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=sessions_dot_sessions__pb2.GetSessions.FromString,
                    response_serializer=sessions_dot_sessions__pb2.Sessions.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=sessions_dot_sessions__pb2.Session.FromString,
                    response_serializer=sessions_dot_sessions__pb2.DeleteResponse.SerializeToString,
            ),
            'GetActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivity,
                    request_deserializer=sessions_dot_sessions__pb2.GetActivityRequest.FromString,
                    response_serializer=sessions_dot_sessions__pb2.Activity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nocloud.sessions.SessionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nocloud.sessions.SessionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nocloud.sessions.SessionsService/Get',
            sessions_dot_sessions__pb2.GetSessions.SerializeToString,
            sessions_dot_sessions__pb2.Sessions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nocloud.sessions.SessionsService/Revoke',
            sessions_dot_sessions__pb2.Session.SerializeToString,
            sessions_dot_sessions__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nocloud.sessions.SessionsService/GetActivity',
            sessions_dot_sessions__pb2.GetActivityRequest.SerializeToString,
            sessions_dot_sessions__pb2.Activity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
