//
//Copyright © 2021-2023 Nikita Ivanovski info@slnt-opp.xyz
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file settings/settings.proto (package nocloud.settings, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteRequest, DeleteResponse, GetRequest, KeyEvent, KeysRequest, KeysResponse, PutRequest, PutResponse } from "./settings_pb.js";
import { MethodKind, Struct } from "@bufbuild/protobuf";

/**
 * @generated from service nocloud.settings.SettingsService
 */
export const SettingsService = {
  typeName: "nocloud.settings.SettingsService",
  methods: {
    /**
     * @generated from rpc nocloud.settings.SettingsService.Get
     */
    get: {
      name: "Get",
      I: GetRequest,
      O: Struct,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.settings.SettingsService.Put
     */
    put: {
      name: "Put",
      I: PutRequest,
      O: PutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.settings.SettingsService.Sub
     */
    sub: {
      name: "Sub",
      I: GetRequest,
      O: KeyEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc nocloud.settings.SettingsService.Keys
     */
    keys: {
      name: "Keys",
      I: KeysRequest,
      O: KeysResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.settings.SettingsService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteRequest,
      O: DeleteResponse,
      kind: MethodKind.Unary,
    },
  }
};

