<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: access/access.proto

namespace Nocloud\Access\GPBMetadata;

class Access
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFB\x03\x0A\x13access/access.proto\x12\x0Enocloud.access\"\x96\x01\x0A\x06Access\x12+\x0A\x05level\x18\x01 \x01(\x0E2\x15.nocloud.access.LevelR\x05level\x12\x12\x0A\x04role\x18\x02 \x01(\x09R\x04role\x12!\x0A\x09namespace\x18\x03 \x01(\x09H\x00R\x09namespace\x88\x01\x01\x12\x1A\x0A\x08username\x18\x04 \x01(\x09R\x08usernameB\x0C\x0A\x0A_namespace\"F\x0A\x04Node\x12\x12\x0A\x04node\x18\x01 \x01(\x09R\x04node\x12\x16\x0A\x06parent\x18\x02 \x01(\x09R\x06parent\x12\x12\x0A\x04edge\x18\x03 \x01(\x09R\x04edge\"3\x0A\x05Nodes\x12*\x0A\x05nodes\x18\x01 \x03(\x0B2\x14.nocloud.access.NodeR\x05nodes*:\x0A\x05Level\x12\x08\x0A\x04NONE\x10\x00\x12\x08\x0A\x04READ\x10\x01\x12\x08\x0A\x04MGMT\x10\x02\x12\x09\x0A\x05ADMIN\x10\x03\x12\x08\x0A\x04ROOT\x10\x04Bz\x0A\x12com.nocloud.accessB\x0BAccessProtoP\x01\xA2\x02\x03NAX\xAA\x02\x0ENocloud.Access\xCA\x02\x0ENocloud\\Access\xE2\x02\x1ANocloud\\Access\\GPBMetadata\xEA\x02\x0FNocloud::Accessb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

