<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing/billing.proto

namespace Nocloud\Billing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.billing.CostEstimation</code>
 */
class CostEstimation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, double> resources = 1 [json_name = "resources"];</code>
     */
    private $resources;
    /**
     * Generated from protobuf field <code>double product = 2 [json_name = "product"];</code>
     */
    protected $product = 0.0;
    /**
     * Generated from protobuf field <code>double total = 3 [json_name = "total"];</code>
     */
    protected $total = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $resources
     *     @type float $product
     *     @type float $total
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Billing\GPBMetadata\Billing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, double> resources = 1 [json_name = "resources"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getResources()
    {
        return $this->resources;
    }

    /**
     * Generated from protobuf field <code>map<string, double> resources = 1 [json_name = "resources"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setResources($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->resources = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double product = 2 [json_name = "product"];</code>
     * @return float
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Generated from protobuf field <code>double product = 2 [json_name = "product"];</code>
     * @param float $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkDouble($var);
        $this->product = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total = 3 [json_name = "total"];</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>double total = 3 [json_name = "total"];</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

}

