<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: billing/billing.proto

namespace Nocloud\Billing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.billing.GetExchangeRatesResponse</code>
 */
class GetExchangeRatesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .nocloud.billing.GetExchangeRateResponse rates = 1 [json_name = "rates"];</code>
     */
    private $rates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Nocloud\Billing\GetExchangeRateResponse>|\Google\Protobuf\Internal\RepeatedField $rates
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Billing\GPBMetadata\Billing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .nocloud.billing.GetExchangeRateResponse rates = 1 [json_name = "rates"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRates()
    {
        return $this->rates;
    }

    /**
     * Generated from protobuf field <code>repeated .nocloud.billing.GetExchangeRateResponse rates = 1 [json_name = "rates"];</code>
     * @param array<\Nocloud\Billing\GetExchangeRateResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nocloud\Billing\GetExchangeRateResponse::class);
        $this->rates = $arr;

        return $this;
    }

}

