<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing/billing.proto

namespace Nocloud\Billing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.billing.InstanceReport</code>
 */
class InstanceReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1 [json_name = "uuid"];</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>double total = 2 [json_name = "total"];</code>
     */
    protected $total = 0.0;
    /**
     * Generated from protobuf field <code>.nocloud.billing.Currency currency = 3 [json_name = "currency"];</code>
     */
    protected $currency = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type float $total
     *     @type \Nocloud\Billing\Currency $currency
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Billing\GPBMetadata\Billing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1 [json_name = "uuid"];</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1 [json_name = "uuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total = 2 [json_name = "total"];</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>double total = 2 [json_name = "total"];</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nocloud.billing.Currency currency = 3 [json_name = "currency"];</code>
     * @return \Nocloud\Billing\Currency|null
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    public function hasCurrency()
    {
        return isset($this->currency);
    }

    public function clearCurrency()
    {
        unset($this->currency);
    }

    /**
     * Generated from protobuf field <code>.nocloud.billing.Currency currency = 3 [json_name = "currency"];</code>
     * @param \Nocloud\Billing\Currency $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkMessage($var, \Nocloud\Billing\Currency::class);
        $this->currency = $var;

        return $this;
    }

}

