<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing/billing.proto

namespace Nocloud\Billing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.billing.PaymentGateway</code>
 */
class PaymentGateway extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bool enabled = 2 [json_name = "enabled"];</code>
     */
    protected $enabled = false;
    /**
     * Display info based on language code
     *
     * Generated from protobuf field <code>map<string, .nocloud.billing.PaymentGatewayDisplay> language_display = 3 [json_name = "languageDisplay"];</code>
     */
    private $language_display;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type bool $enabled
     *     @type array|\Google\Protobuf\Internal\MapField $language_display
     *           Display info based on language code
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Billing\GPBMetadata\Billing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 2 [json_name = "enabled"];</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 2 [json_name = "enabled"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Display info based on language code
     *
     * Generated from protobuf field <code>map<string, .nocloud.billing.PaymentGatewayDisplay> language_display = 3 [json_name = "languageDisplay"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLanguageDisplay()
    {
        return $this->language_display;
    }

    /**
     * Display info based on language code
     *
     * Generated from protobuf field <code>map<string, .nocloud.billing.PaymentGatewayDisplay> language_display = 3 [json_name = "languageDisplay"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLanguageDisplay($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nocloud\Billing\PaymentGatewayDisplay::class);
        $this->language_display = $arr;

        return $this;
    }

}

