<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing/billing.proto

namespace Nocloud\Billing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.billing.PlansUniqueRequest</code>
 */
class PlansUniqueRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sp_uuid = 1 [json_name = "spUuid"];</code>
     */
    protected $sp_uuid = '';
    /**
     * Generated from protobuf field <code>bool anonymously = 2 [json_name = "anonymously"];</code>
     */
    protected $anonymously = false;
    /**
     * Generated from protobuf field <code>bool show_deleted = 3 [json_name = "showDeleted"];</code>
     */
    protected $show_deleted = false;
    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> filters = 4 [json_name = "filters"];</code>
     */
    private $filters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sp_uuid
     *     @type bool $anonymously
     *     @type bool $show_deleted
     *     @type array|\Google\Protobuf\Internal\MapField $filters
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Billing\GPBMetadata\Billing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sp_uuid = 1 [json_name = "spUuid"];</code>
     * @return string
     */
    public function getSpUuid()
    {
        return $this->sp_uuid;
    }

    /**
     * Generated from protobuf field <code>string sp_uuid = 1 [json_name = "spUuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setSpUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->sp_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool anonymously = 2 [json_name = "anonymously"];</code>
     * @return bool
     */
    public function getAnonymously()
    {
        return $this->anonymously;
    }

    /**
     * Generated from protobuf field <code>bool anonymously = 2 [json_name = "anonymously"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAnonymously($var)
    {
        GPBUtil::checkBool($var);
        $this->anonymously = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool show_deleted = 3 [json_name = "showDeleted"];</code>
     * @return bool
     */
    public function getShowDeleted()
    {
        return $this->show_deleted;
    }

    /**
     * Generated from protobuf field <code>bool show_deleted = 3 [json_name = "showDeleted"];</code>
     * @param bool $var
     * @return $this
     */
    public function setShowDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->show_deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> filters = 4 [json_name = "filters"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> filters = 4 [json_name = "filters"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFilters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
        $this->filters = $arr;

        return $this;
    }

}

