<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing/billing.proto

namespace Nocloud\Billing;

use UnexpectedValueException;

/**
 * Protobuf type <code>nocloud.billing.Round</code>
 */
class Round
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>FLOOR = 1;</code>
     */
    const FLOOR = 1;
    /**
     * Generated from protobuf enum <code>ROUND = 2;</code>
     */
    const ROUND = 2;
    /**
     * Generated from protobuf enum <code>CEIL = 3;</code>
     */
    const CEIL = 3;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::FLOOR => 'FLOOR',
        self::ROUND => 'ROUND',
        self::CEIL => 'CEIL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

