<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cc/chats.proto

namespace Nocloud\Cc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.cc.ListChatMessagesRequest</code>
 */
class ListChatMessagesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string chatUuid = 1 [json_name = "chatUuid"];</code>
     */
    protected $chatUuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $chatUuid
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Cc\GPBMetadata\Chats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string chatUuid = 1 [json_name = "chatUuid"];</code>
     * @return string
     */
    public function getChatUuid()
    {
        return $this->chatUuid;
    }

    /**
     * Generated from protobuf field <code>string chatUuid = 1 [json_name = "chatUuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setChatUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->chatUuid = $var;

        return $this;
    }

}

