//
//Copyright © 2021-2023 Nikita Ivanovski info@slnt-opp.xyz
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file services/services.proto (package nocloud.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateRequest, DeleteRequest, DeleteResponse, DownRequest, DownResponse, GetRequest, ListRequest, Service, Services, StreamRequest, SuspendRequest, SuspendResponse, TestConfigResponse, UnsuspendRequest, UnsuspendResponse, UpRequest, UpResponse } from "./services_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ObjectState } from "../states/states_pb.js";

/**
 * @generated from service nocloud.services.ServicesService
 */
export const ServicesService = {
  typeName: "nocloud.services.ServicesService",
  methods: {
    /**
     * @generated from rpc nocloud.services.ServicesService.TestConfig
     */
    testConfig: {
      name: "TestConfig",
      I: CreateRequest,
      O: TestConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Create
     */
    create: {
      name: "Create",
      I: CreateRequest,
      O: Service,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Update
     */
    update: {
      name: "Update",
      I: Service,
      O: Service,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteRequest,
      O: DeleteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Get
     */
    get: {
      name: "Get",
      I: GetRequest,
      O: Service,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: Services,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Up
     */
    up: {
      name: "Up",
      I: UpRequest,
      O: UpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Down
     */
    down: {
      name: "Down",
      I: DownRequest,
      O: DownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Suspend
     */
    suspend: {
      name: "Suspend",
      I: SuspendRequest,
      O: SuspendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Unsuspend
     */
    unsuspend: {
      name: "Unsuspend",
      I: UnsuspendRequest,
      O: UnsuspendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nocloud.services.ServicesService.Stream
     */
    stream: {
      name: "Stream",
      I: StreamRequest,
      O: ObjectState,
      kind: MethodKind.ServerStreaming,
    },
  }
};

