<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instances/instances.proto

namespace Nocloud\Instances;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.instances.Context</code>
 */
class Context extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nocloud.instances.Instance instance = 1 [json_name = "instance"];</code>
     */
    protected $instance = null;
    /**
     * Generated from protobuf field <code>.nocloud.services_providers.ServicesProvider sp = 2 [json_name = "sp"];</code>
     */
    protected $sp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nocloud\Instances\Instance $instance
     *     @type \Nocloud\ServicesProviders\ServicesProvider $sp
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Instances\GPBMetadata\Instances::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nocloud.instances.Instance instance = 1 [json_name = "instance"];</code>
     * @return \Nocloud\Instances\Instance|null
     */
    public function getInstance()
    {
        return $this->instance;
    }

    public function hasInstance()
    {
        return isset($this->instance);
    }

    public function clearInstance()
    {
        unset($this->instance);
    }

    /**
     * Generated from protobuf field <code>.nocloud.instances.Instance instance = 1 [json_name = "instance"];</code>
     * @param \Nocloud\Instances\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Nocloud\Instances\Instance::class);
        $this->instance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nocloud.services_providers.ServicesProvider sp = 2 [json_name = "sp"];</code>
     * @return \Nocloud\ServicesProviders\ServicesProvider|null
     */
    public function getSp()
    {
        return $this->sp;
    }

    public function hasSp()
    {
        return isset($this->sp);
    }

    public function clearSp()
    {
        unset($this->sp);
    }

    /**
     * Generated from protobuf field <code>.nocloud.services_providers.ServicesProvider sp = 2 [json_name = "sp"];</code>
     * @param \Nocloud\ServicesProviders\ServicesProvider $var
     * @return $this
     */
    public function setSp($var)
    {
        GPBUtil::checkMessage($var, \Nocloud\ServicesProviders\ServicesProvider::class);
        $this->sp = $var;

        return $this;
    }

}

