<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instances/instances.proto

namespace Nocloud\Instances;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nocloud.instances.TestInstancesGroupConfigRequest</code>
 */
class TestInstancesGroupConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nocloud.instances.InstancesGroup group = 1 [json_name = "group"];</code>
     */
    protected $group = null;
    /**
     * Generated from protobuf field <code>.nocloud.services_providers.ServicesProvider sp = 2 [json_name = "sp"];</code>
     */
    protected $sp = null;
    /**
     * UUIDs of instances to estimate cost
     *
     * Generated from protobuf field <code>repeated string estimate_instances = 3 [json_name = "estimateInstances"];</code>
     */
    private $estimate_instances;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nocloud\Instances\InstancesGroup $group
     *     @type \Nocloud\ServicesProviders\ServicesProvider $sp
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $estimate_instances
     *           UUIDs of instances to estimate cost
     * }
     */
    public function __construct($data = NULL) {
        \Nocloud\Instances\GPBMetadata\Instances::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nocloud.instances.InstancesGroup group = 1 [json_name = "group"];</code>
     * @return \Nocloud\Instances\InstancesGroup|null
     */
    public function getGroup()
    {
        return $this->group;
    }

    public function hasGroup()
    {
        return isset($this->group);
    }

    public function clearGroup()
    {
        unset($this->group);
    }

    /**
     * Generated from protobuf field <code>.nocloud.instances.InstancesGroup group = 1 [json_name = "group"];</code>
     * @param \Nocloud\Instances\InstancesGroup $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkMessage($var, \Nocloud\Instances\InstancesGroup::class);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nocloud.services_providers.ServicesProvider sp = 2 [json_name = "sp"];</code>
     * @return \Nocloud\ServicesProviders\ServicesProvider|null
     */
    public function getSp()
    {
        return $this->sp;
    }

    public function hasSp()
    {
        return isset($this->sp);
    }

    public function clearSp()
    {
        unset($this->sp);
    }

    /**
     * Generated from protobuf field <code>.nocloud.services_providers.ServicesProvider sp = 2 [json_name = "sp"];</code>
     * @param \Nocloud\ServicesProviders\ServicesProvider $var
     * @return $this
     */
    public function setSp($var)
    {
        GPBUtil::checkMessage($var, \Nocloud\ServicesProviders\ServicesProvider::class);
        $this->sp = $var;

        return $this;
    }

    /**
     * UUIDs of instances to estimate cost
     *
     * Generated from protobuf field <code>repeated string estimate_instances = 3 [json_name = "estimateInstances"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEstimateInstances()
    {
        return $this->estimate_instances;
    }

    /**
     * UUIDs of instances to estimate cost
     *
     * Generated from protobuf field <code>repeated string estimate_instances = 3 [json_name = "estimateInstances"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEstimateInstances($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->estimate_instances = $arr;

        return $this;
    }

}

