name: Generate Protobuf Client Libraries for PHP
on:
  pull_request_target:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find and Replace swagger options
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "(    option \\(google\\.api\\.http\\) = \\{\n((.|\n)*?)    \\};)"
          replace: "\n"
          regex: true
      - name: Find and Replace swagger imports
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "import \"google/api/annotations.proto\";"
          replace: "\n"
          regex: false
      
      # - name: (debug) Check if swagger options are removed
      #   run: |
      #     echo "### dns.proto" >> $GITHUB_STEP_SUMMARY
      #     echo '```protobuf' >> $GITHUB_STEP_SUMMARY
      #     cat dns/dns.proto >$GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: '8.2'
          tools: composer, grpc_php_plugin
      
      # - name: (debug) Check grpc_php_plugin location
      #   run: |
      #     echo "### grpc_php_plugin location" >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      #     echo "$(which grpc_php_plugin)" >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      
      - name: Setup Buf Cli
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Protobuf Client Libraries
        run: |
          buf generate --template buf.gen.php.yaml

      - name: (debug) Check if generated files are correct
        run: |
          echo "### Generated files" >> $GITHUB_STEP_SUMMARY
          echo '```protobuf' >> $GITHUB_STEP_SUMMARY
          echo "$(git status)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: GIT commit and push
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Protobuf Client Libraries for PHP
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "team@nocloud.zone"
          git add proto/php
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push